# Generated by Django 2.0.6 on 2019-05-26 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, max_length=300, null=True)),
                ('direccion', models.CharField(max_length=200, null=True)),
                ('ruc', models.CharField(max_length=50, null=True, unique=True)),
                ('telefono', models.CharField(max_length=30)),
            ],
        ),
    ]
