# Generated by Django 3.2.5 on 2021-12-05 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='fecha',
            field=models.DateTimeField(default='2006-10-25 14:30:59'),
        ),
    ]
