# Generated by Django 3.2.5 on 2021-12-05 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstory', '0002_alter_actividad_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
